logoutput: syslog
user.privileged: root
user.unprivileged: nobody

# The listening network interface or address.
internal: 0.0.0.0 port=41080
internal: :: port=41080

# The proxying network interface or address.
external: enp1s0

# socks-rules determine what is proxied through the external interface.
socksmethod: none username
#socksmethod: username
#socksmethod: none

# client-rules determine who can connect to the internal interface.
clientmethod: none
#clientmethod: username

# ---- TẦNG 1: CLIENT RULES (Vòng gửi xe - Nhẹ resource nhất) ----

# Cho phép IP Win Server của bạn và IP nhà bạn chạm vào cổng proxy
# client pass {
#     from: 14.169.243.19/32 to: 0.0.0.0/0
# }
# client pass {
#     from: 159.195.9.0/24 to: 0.0.0.0/0
# }

client pass {
    from: 0.0.0.0/0
    to: 0.0.0.0/0
}

client pass {
    from: ::/0
    to: ::/0
}

# CẤM TIỆT tất cả các IP khác trên thế giới kết nối vào cổng 41080
# Thằng nào không nằm trong 2 dải trên sẽ bị ngắt ngay tại đây, không tốn 1 tí CPU nào cho tầng SOCKS bên dưới.
# client block {
#     from: 0.0.0.0/0 to: 0.0.0.0/0
#     log: connect error
# }


# ---- TẦNG 2: SOCKS RULES (Vòng trong - Phân loại xử lý) ----

# IP cụ thể này của bạn dính rule này -> Vào thẳng không pass
socks pass {
    from: 1.1.1.1/32
    to: 0.0.0.0/0
    socksmethod: none
}

socks pass {
    from: 1.1.1.1/32
    to: ::/0
    socksmethod: none
}

# Dải IP này của bạn dính rule này -> Bắt nhập User/Pass để bảo mật nâng cao
socks pass {
    from: 0.0.0.0/0
    to: 0.0.0.0/0
    socksmethod: username
}

socks pass {
    from: 0.0.0.0/0
    to: ::/0
    socksmethod: username
}

socks pass {
    from: ::/0
    to: ::/0
    socksmethod: username
}